### ISSUE TITLE
Uniform Coding Style

### ISSUE THREAD

**Issue by Gemba** [BenoitDuffez/AndroidCupsPrint#10]
For a better maintenance and to make it easier for contributors it would be useful to have a uniform coding style. There is a mix between Jon Freemans code and yours. I have no specific preference as long as it is a consistent style.

**Comment by BenoitDuffez** [comment]
Better now?

**Comment by Gemba** [comment]
Yep, thx. For the braces aso. I will follow the local style found in the classes authored by you.

For me it is okay to close this issue.
