### ISSUE TITLE
Issues Printing

### ISSUE THREAD

**Issue by Liboicl** [BenoitDuffez/AndroidCupsPrint#102]
It works sometimes, but rarely. I've dumped the network traffic when it doesn't work. Thanks in advance for the help.

[CUPS.txt](https://github.com/BenoitDuffez/AndroidCupsPrint/files/1933752/CUPS.txt)

**Comment by BenoitDuffez** [comment]
It looks like your server uses CUPS v1.5, is there any reason for that? Can you try to update your CUPS version to something more recent and see if this helps?

**Comment by BenoitDuffez** [comment]
Can you reproduce the issue on the most recent version of CUPS?

**Comment by BenoitDuffez** [comment]
Please reopen if you have more logs: server logs, logcat. The network dump is nice but I don't really understand what happens.
