### ISSUE TITLE
New logo desing for CUPS Printing

### ISSUE THREAD

**Issue by sametceylan** [BenoitDuffez/AndroidCupsPrint#103]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for Cups Print. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by BenoitDuffez** [comment]
So nice! Yes!

I have no particular detail, other than the fact that it must look like or follow the guidelines for material design, and optionally represent a printer (I guess that's almost mandatory but why not something else).

Feel free to do what you want, you are the creative mind :)

**Comment by BenoitDuffez** [comment]
Can you still do it?

**Comment by BenoitDuffez** [comment]
I'm still up for this, but I don't want to keep dead issues alive. Please reopen if you can make this happen.
