### ISSUE TITLE
No authenticated printing support

### ISSUE THREAD

**Issue by shawnl** [BenoitDuffez/AndroidCupsPrint#106]
Under the CUPS html settings I set Operation Policy: Authenticated, and this driver no longer works, with error message: "Couldn't handle job"

It would have to query for a user-name and password somehow.

**Comment by BenoitDuffez** [comment]
Do you have a pcap or à log that would help me understand what's going on?

**Comment by shawnl** [comment]
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
	<TITLE>Upgrade Required - CUPS v2.2.7</TITLE>
	<LINK REL="STYLESHEET" TYPE="text/css" HREF="/cups.css">
<META HTTP-EQUIV="Refresh" CONTENT="3;URL=https://10.1.10.144:631/printers/Brother_HL-L2390DW">
</HEAD>
<BODY>
<H1>Upgrade Required</H1>
<P>You must access this page using the URL <A HREF="https://10.1.10.144:631/printers/Brother_HL-L2390DW">https://10.1.10.144:631/printers/Brother_HL-L2390DW</A>.</P>
</BODY>
</HTML>`

**Comment by BenoitDuffez** [comment]
I see. You need to change the printer URL to use https. Or change the mDNS/whatever configuration to advertise the https URL over the http one.

**Comment by BenoitDuffez** [comment]
Did you manage to fix this?

**Comment by BenoitDuffez** [comment]
This doesn't provide enough information, HTTP basic auth is supported and the error seems to be about the wrong use of plain HTTP. Please reopen if you have more details to share.
