### ISSUE TITLE
Severe influence on battery life

### ISSUE THREAD

**Issue by nimra98** [BenoitDuffez/AndroidCupsPrint#107]
Using the App on a LG G4 with Android 6.0 (Patchlevel 2016-07-01) stock firmware, it had major influence on my battery life. It nearly halved the runtime in Standby.
Is it possible that AudoDiscovery may have a influence on that?
I have a Brother HL2250DN, Brother MFC5890CN and an Epson SX420W, which are all used via a CUPS server.

**Comment by BenoitDuffez** [comment]
Auto discovery is turned on only when printing. The app doesn't do anything when not printing. Maybe a bogus print job that got stuck and kept the device from sleeping?

**Comment by nimra98** [comment]
I had one job, which didn't went through. I'm not sure, whether I restarted the device after that.
I will monitor the situation.

**Comment by BenoitDuffez** [comment]
Please let me know whether this is still an issue.

**Comment by nimra98** [comment]
I'm honestly not sure. 
When I went on holiday last week and turned off Wifi it seemed like the battery was decharging much slower, although I used locations services as well.
So for me it looks  either like a general Wifi-Battery-thing with my phone or your app does at least contribute to it.
I'd say, if you don't have an idea what the reason could be and there are no others with the same issue, it's not worth investigating.

**Comment by BenoitDuffez** [comment]
You could always try to get the device logs using logcat, and grep on CUPS; or use pidcat on `io.github.benoitduffez.cupsprint` and see if there is any logging.

My guess is that there would be none (unless you're printing something), and that the app isn't even started.

Anyway thanks for your feedback. Closing for now, feel free to comment if you think this needs further investigation.
