### ISSUE TITLE
Uniform License 

### ISSUE THREAD

**Issue by Gemba** [BenoitDuffez/AndroidCupsPrint#11]
There is a mix between LGPL v2.1 and LGPL v3. Do you mind relicensing the LGPL v2.1 parts to LGPL v3? (Benefit: Single file header, lesser files: COPYING.v2.1 and COPYING.LESSER.v2.1 can be omitted)

**Comment by BenoitDuffez** [comment]
I am no license expert, don't really know the difference between v2 and v3, and I have no preference in either of them.
My only goal are to respect Jon's license, and publish as open source and free to use.
If you think you can improve the license, feel free to submit a PR.

**Comment by BenoitDuffez** [comment]
Hey, what would switching to LGPL v3 imply? Only a change in the README file? Or additional headers/LICENSE file/something?
Thanks

**Comment by Gefrierbrand** [comment]
LGPL 2.1 allows you to use any later version of the licence. So any file licenced under it is compatible with the ones licenced under the version 3. For details you should check gnu.org

**Comment by BenoitDuffez** [comment]
I guess that's uniform now. Please comment if you think it's not.
