### ISSUE TITLE
Error of bad file descriptor

### ISSUE THREAD

**Issue by chrisapps4u** [BenoitDuffez/AndroidCupsPrint#116]
Every time i try to print on my cups server, i get this error.

![screenshot_20180720-174904](https://user-images.githubusercontent.com/43114622/45639535-8ef17780-bab0-11e8-99b2-f89d92dc3af9.jpg)

**Comment by chrisapps4u** [comment]
I found the problem in the code. In case of small memory the garbage collector automatically close the FileDescriptor in printDocument, because "data" don't have a reference any more. See #117

**Comment by petronem** [comment]
I was getting the same EBADF message and just installed the beta through the Play Store. Here's a different message:
![image](https://user-images.githubusercontent.com/22941760/46052527-dad59980-c10c-11e8-943c-ba0319c6e4eb.png)

**Comment by chrisapps4u** [comment]
This error was fixed with #115.
@BenoitDuffez could you merge this version to beta branch and load it into Play Store?

**Comment by BenoitDuffez** [comment]
Actually you have a beta as a nightly build every day if there are new commits on develop...

...but the last commit broke the build with the bogus import so no build = no beta 👎 

I'll fix this in a minute

**Comment by BenoitDuffez** [comment]
Merged
