### ISSUE TITLE
Delete a manually added CUPS printer?

### ISSUE THREAD

**Issue by rcpao** [BenoitDuffez/AndroidCupsPrint#119]
How do I delete a manually added CUPS printer?  Long press on it does not bring up a Delete/Remove option.

**Comment by macearl** [comment]
a simple tap should do it

**Comment by BenoitDuffez** [comment]
Short press / tap it

**Comment by rcpao** [comment]
Searching returns two lines for the same printer: one matches CUPS Admin Printer Description field@hostname, the other matches the manually added name for the same.  If I quick tap or long tap either, nothing happens.

Apparently, I didn't want long enough for Searching to return something back to me so I manually added it. I didn't see a spinner or progress bar advancing so it didn't look like it was doing anything.

OnePlus 6, OxygenOS 5.1.11, Android 8.1.0.

**Comment by BenoitDuffez** [comment]
You should open the app, you would be presented with the list of the _manually entered_ printers only. Tap it, it's gone.

**Comment by rcpao** [comment]
Oops.  I didn't realize there was an actual App added to the Apps List.  I assumed the only interface was in Settings > Advanced > Printing > Android CUPS Print, and the only list was from "Searching for printers".

Perfect for me now.  I removed my note/question in the review.  Thanks for allowing my Androids to print to my ancient LaserJet!

**Comment by BenoitDuffez** [comment]
Hehe no worries!

Have a good one.

**Comment by macearl** [comment]
> You should open the app, you would be presented with the list of the _manually entered_ printers only. Tap it, it's gone.

for me its a list of all printers, not only manually added
