### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [BenoitDuffez/AndroidCupsPrint#132]
Please add support for icon shape

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by BenoitDuffez** [comment]
The icon is not very suited to be adaptive.

![screen shot 2018-11-29 at 20 30 09](https://user-images.githubusercontent.com/802209/49246605-a4224500-f415-11e8-8e9f-fdb57390abfb.png)

Do you think this icon would be better?

**Comment by 532910** [comment]
> Do you think this icon would be better?

Yes!

**Comment by 532910** [comment]
Thank you!
