### ISSUE TITLE
java.lang.IllegalStateException: No media size specified.

### ISSUE THREAD

**Issue by returntoreality** [BenoitDuffez/AndroidCupsPrint#19]
I have the following issue: The printer is detected, but it is "currently not available". The logcat shows the following two entries:

```
09-20 20:25:59.294  8039 26272 I CUPS    : Checking printer status: PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://192.168.42.9:631/printers/HP_LaserJet_6MP}
09-20 20:25:59.377  8039 26272 E CUPS    : Failed to check printer PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://192.168.42.9:631/printers/HP_LaserJet_6MP}: java.lang.IllegalStateException: No media size specified.
```

In the CUPS webinterface the defaults are shown as follows:
Defaults:   job-sheets=none, none media=iso_a4_210x297mm sides=one-sided

**Comment by BenoitDuffez** [comment]
Could you try again with the latest beta version? It has better error reporting so I can fully understand what's going on here. Thanks

**Comment by BenoitDuffez** [comment]
Also, could you share more details about your setup? Phone, Android version, language, etc.
Do you use simplified Chinese? see: https://code.google.com/p/android/issues/detail?id=82811

**Comment by returntoreality** [comment]
It works with the beta version, so I'm closing the issue. Thanks for pointing out the beta, and this app!

**Comment by BenoitDuffez** [comment]
Thanks for the feedback
