### ISSUE TITLE
Old gradle version is been used, fix breaking changes in build.gradle

### ISSUE THREAD

**Issue by Zeratoxx** [BenoitDuffez/AndroidCupsPrint#190]
file `[projRoot]/app/build.gradle:106-108`: replace `sourceDirectories = files([mainSrc])` with `getSourceDirectories().setFrom( files([mainSrc]) )` and matching that sceme the two following lines also.

More information accordings that here: https://docs.gradle.org/current/userguide/upgrading_version_5.html#other_deprecated_behaviors_and_apis

**Comment by BenoitDuffez** [comment]
Thanks for fixing this in #192
