### ISSUE TITLE
how to build a cups service on an Android device

### ISSUE THREAD

**Issue by MacSheo** [BenoitDuffez/AndroidCupsPrint#196]
I want to know how to build a cups service on an Android device. Cross-compilation is too difficult and there are many bugs. Currently, one solution is to deploy the cups service on Ubuntu, and the other solution is to install Termux on Android and then install cups, but it seems that it cannot be started. It is too difficult. Is there any good tutorial or other better solution?

**Comment by BenoitDuffez** [comment]
CUPS is used to manage printers, so unless you physically connect printers to your Android device, this will not help you.

Network printers usually already have some kind of CUPS daemon.
