### ISSUE TITLE
Certificate management

### ISSUE THREAD

**Issue by BenoitDuffez** [BenoitDuffez/AndroidCupsPrint#2]
Add a UI to manage self signed certificates for printers over `https`.

**Comment by Gemba** [comment]
I can implement this if you don't mind. Rough sketch:

1. User gets prompted upon cert error
2. If she agrees with "accept permanently" no further prompts occur from this site

Later there may be an option useful to forget/delete permanently accepted certs, also an preference setting "use SSL, if available" will be useful.

**Comment by BenoitDuffez** [comment]
Of course, please do!
Also, when I removed code from JfCupsPrint, there was some code managing self-signed certs. Maybe that can be source of inspiration.

**Comment by BenoitDuffez** [comment]
This was implemented in f7ed730.
