### ISSUE TITLE
Min API level

### ISSUE THREAD

**Issue by 9662** [BenoitDuffez/AndroidCupsPrint#24]
Hello Benoît, and thanks for taking over maintenance of this application!

Is there any chance that the minimum API level could be lowered to 17, so as to support Android 4.2.1?

**Comment by BenoitDuffez** [comment]
Sorry, the main goal of this app is to use the Android Print Service, which was added in API 19.

https://developer.android.com/reference/android/printservice/package-summary.html

**Comment by 9662** [comment]
I see, cheers.
