### ISSUE TITLE
Remove printers

### ISSUE THREAD

**Issue by sedrubal** [BenoitDuffez/AndroidCupsPrint#26]
I can't find a way to remove added printers.

**Comment by pvagner** [comment]
I think a workaround can be made as follows:
* On your Android device go to Settings -> Apps -> Android Cups Print
*- Clear all the data.

If an avahi or similar DNS SD service is running on the network the list can be easily populated on the next run.

**Comment by sedrubal** [comment]
Yes this works but is very inconvenient...

**Comment by BenoitDuffez** [comment]
I know, but I don't have time to work on this. Submit a PR if you have time.
Cheers
