### ISSUE TITLE
Doesn't show all printers on a server

### ISSUE THREAD

**Issue by speachy** [BenoitDuffez/AndroidCupsPrint#27]
I have a setup where I have ten printers plugged into a single CUPS instance.  However, only two of them show up when the AndroidCUPSPrint plugin searches for local printers.

This is with the current 1.3.1 release (obtained via f-droid), running on CM12.1 (Android 5.1.1) talking to a CUPS 2.2.0 server.  All printers are exported/shared, and Linux desktops see them.

Why ten printers, you may ask?  I write printer drivers (Gutenprint) for fun and occasional profit.

**Comment by BenoitDuffez** [comment]
Can you share your server logs, if possible a tcpdump of the traffic when the app is discovering, and possibly the device logcat?
I only have one printer installed :)

**Comment by speachy** [comment]
I'm overseas right now, but I'll get to this when I get back home.

**Comment by speachy** [comment]
[scan.zip](https://github.com/BenoitDuffez/AndroidCupsPrint/files/765702/scan.zip)

Sorry about the delay -- Finally was able to sit down and do the packet capture.  I performed the scan several times.  The sniff shows the MDNS query and responses.  

It appears that all nine attached printers are included in the responses, but those responses are split across five MDNS response packets. The AndroidCUPSPrint plugin is only showing printers that were in the first of those five packets.

**Comment by BenoitDuffez** [comment]
Thanks a lot for the effort you put into this. I'll definitely have a look on this the next time I have some time to work on this project.

**Comment by speachy** [comment]
I'm the one who should be thanking you -- this is the only non-proprietary CUPS plugin -- not only from a code perspective, but it also doesn't rely on a proprietary cloud service of some sort.

I'll see if I can have a look at the code too; it's been 15 years since I last touched java but I am pretty familiar with mDNS.

**Comment by speachy** [comment]
Onn line 195 of app/src/main/java/io/github/benoitduffez/cupsprint/detect/MdnsServices.java, the number of iterations of the listen/process loop is capped at 1.   That completely explains my observations.

Since you already have a socket timeout in place, IMO the number of iterations should be bumped to something much larger -- eg 100.   An alternative is to remove the cap altogether, and use a global timer to ensure no more than, say, 5 seconds in total is spent scanning.

**Comment by BenoitDuffez** [comment]
Actually at this line there is no cap, it's just the starting point (e.g "1st attempt"). The cap is set at 50 tries.
I can at least spot that there is an exception that is silently ignored, that's bad. It should be at least logged, and possibly sent to us (developers) if it's not too common.

This exception should be valuable because I think it's the cap that's being hit first (not the `MAX_PASSES`).
Can you build the app with this exception logged? I could provide you with an APK if necessary.

**Comment by speachy** [comment]
I don't currently have an environment that can compile android apps, so I'd appreciate it if you could supply an APK with that exception logged.

**Comment by BenoitDuffez** [comment]
Sorry for the delay. Here's a debug build, please uninstall the app before trying to install this one (it isn't signed so you wouldn't be able to install it over the existing app).
It should automatically send me the exceptions to Fabric.io, so just tell me when you reproduced and I'll have a look at the logs. (or, alternatively, have a look at the Android logs).

[app-debug.apk.zip](https://github.com/BenoitDuffez/AndroidCupsPrint/files/773486/app-debug.apk.zip)

**Comment by speachy** [comment]
[log.txt](https://github.com/BenoitDuffez/AndroidCupsPrint/files/775734/log.txt)

I've attached a scan run with the debug apk.

Interestingly, it shows all the printers being parsed out of mdns, but there's a NullPointerException in the response handling.  Afterwards. only two printers are listed as being discovered.

**Comment by speachy** [comment]
...ping?

**Comment by BenoitDuffez** [comment]
Sorry I saw your log it's very informative but I'm out of time right now. I'll definitely work on this and ping you when that'll be the case.

**Comment by speachy** [comment]
Okay, I've found the source of the problem.  Essentially, the service and name maps are being blown away for each message, but when multiple messages are chained together, they may reference earlier responses.

[fix_multipkt.txt](https://github.com/BenoitDuffez/AndroidCupsPrint/files/800927/fix_multipkt.txt)

I'm too lazy to fork the repo and set up a pull/review request.  So I've attached the patch as a text file instead.  (stupid github..)

I don't know if this is the correct way to solve things (what if we get multiple servers responding with the packets interleaved?) but it at least allows my very voluminous printer list to show up in full.  :)

**Comment by speachy** [comment]
I guess we can close this now.  Any chance of a new release?  :)

**Comment by BenoitDuffez** [comment]
I have worked on the app a bit yesterday, hopefully I will have some time today too to publish an update.
Thanks again for your work on this.

**Comment by BenoitDuffez** [comment]
Commit 8c3d84c5d9bc5424a04b9e15c7770420a354cce0 was published as 1.4.0b1 on the play store as a beta. Please subscribe to betas if you haven't already done so and tell me if it works for you.

Thanks again for your contributions.
