### ISSUE TITLE
Form for non-mDNS enabled CUPS servers

### ISSUE THREAD

**Issue by BenoitDuffez** [BenoitDuffez/AndroidCupsPrint#3]
Several users reported the need to manually add a CUPS server, for those who don't use mDNS.

**Comment by BenoitDuffez** [comment]
Added code in 2f35114d160e64f2478e595ba7fa1f8177d49d5c

Testers welcome.

**Comment by BenoitDuffez** [comment]
Published c2e1679cf1fe1a67a252ecca2ed92b7076655477 on the play store for this.

Feedbacks welcome.

**Comment by SimonButcher** [comment]
Super fast turn-around, thanks Benoit! This small change now makes the app perfect for me. No problems using this with a few different servers, looks good - thanks!

**Comment by BenoitDuffez** [comment]
Thanks for the feedback Simon. Is it working for you? Some users reported it as not working, so I still have some troubleshoot to do (and find some time to do this first!).

**Comment by BenoitDuffez** [comment]
Feedback from an user received on Sep 1st:

> I found your CUPS Printing application for Android - just what I was looking for - thanks. I'm using the 1.2 version with your new form to manually add printers...
> 
> My server's cups daemon is too old to support mDNS currently, hence I need to manually add the printer.
> 
> However, when I enable the CUPS Printing service it automatically starts a printer discover phase, which never completes.
> 
> While the discovery phase is active I can select "add printer", fill out the form and hit the "add printer" button, but (a) I don't see the printer listed, and (b) the discovery phase still continues...
> 
> If I disable the service and try again the same steps repeat.
> 
> On the add printer page I'm pasting a URL copied from the cups server, its a http url on port 631 to the machines dns name. I don't get any error / confirmation from the Add Printer button on this page.
> 
> This is on an ASUS TF300T (if that matters), running Lollipop 5.0.1 - a third party rom called "Katkiss" (if that matters).
> 
> On both my Nexus 6 and Nexus 7, both stock Lollipop 5.1.1 I get the exact same issue.
> 
> All attempts to print from other applications return me to the printer discovery activity.
> 
> I don't see anything server side in the cups daemon logs.
> 
> It seems so close to printing ;-)
> 
> I'd be glad to supply further testing if you have any ideas what is wrong or what I should try next...
> 
> The internal IP address of the server makes no difference either.

**Comment by BenoitDuffez** [comment]
Another feedback received on Aug 30th:

> > 1/ When you add your printer, nothing happens, but the printer is added to the system. When you try to print a document, is it available?
> 
> No, I only have cloud based services from google an samsung available - no local printers.
> However in google print I can add local printer using the same mechanism as in default add rpinter form in Cups Print - but then again nothing happens.
> Samsung's services seems to based entirely on mDNS - there is no manual option.
> I do not know, my problems might be caused by limitation of samusng customizations to android, this has happend before and things working in stock android were not available or were working differently - however, in the past I was able to print to samsung and hp devices that were advertising themselves by mDNS.
> > On my device, when I add the printer it is not instantly visible in the printers list, but it is available when I try to print a document. Maybe it's the same for you?
> 
> It is not available.
> > Also, what URL did you put? On my setup, I can go to http://server:631/ and then I can find my printer, which has a url of http://server:631/printers/PrinterName
> > Is it the same for you when you browse to the CUPS web page on your computer?
> 
> I do gave tried to use the short and long url - nothing happens with either. When using short - nothing happens, I cannot find the printer, when using long nothing happens either.
> The URL is exactly as used by website of local CUPS, and I confirmed the site is reachable form my mobile device's webbrowser.
> > 2/ Crash when name is empty: thanks a lot, I will fix this.
> 
> Thanks to that.

**Comment by fnk0c** [comment]
@BenoitDuffez i am getting the exact problem reported at sep 1. Can add my printer address (http://192.168.0.14:631/printers/Epson_Stylus_TX115) but no confirmation, or fail, is returned. Also it keep searching the printer, but never finds it.

Cups version: 1.7.5 (raspberry build)
Android: Lollipop 
Asus zenfone 5 

Not sure if this information matters.

**Comment by github-k8n** [comment]
Same for me with CUPS 2.1.4 on Gentoo (mDNS disabled), entering the details manually does not help, the search just continues.
This is with CM13 (android 6.0.1) on a Samsung Galaxy Note 4

**Comment by BenoitDuffez** [comment]
It should be fine now, but not for the Play Store version. I didn't know it was so far behind, I'll publish a new version very soon (just waiting for a week or so to get feedback from users on others issues, and on code pushed recently).
So either compile the latest from the develop branch, or wait until the end of the month for a Play Store release.
Sorry it took so long!

**Comment by BenoitDuffez** [comment]
Please test the latest beta on the Play Store. Link is on README file on master.

**Comment by b4free** [comment]
Hi Benoit,
thanks for the work.
Unfortunately I also get the never-ending search for printers, adding manually has no effect.

Is there any chance to get the new code on F-Droid?
I use Android google-free, so no Playstore ...

Regards
  HB

**Comment by BenoitDuffez** [comment]
Did you test with the latest version? Because the beginning of your comment seems to say so, but the end of it seems to tell that you didn't.
Can you provide the logcat of the app while you search and manually add a printer?
Thanks.

**Comment by BenoitDuffez** [comment]
I have submitted a merge request on f-droid to the latest beta version, which seems to be working properly (tag: 1.3.0b2).
See the evolution here: https://gitlab.com/fdroid/fdroiddata/merge_requests/1805
I don't really understand how fdroid works, and gitlab is so slow that it's a huge PITA to use. I hope that what I did was what you wanted (that is: publish the beta on f-droid).

**Comment by b4free** [comment]
Hi Benoit,

wow, that's been quick to respond!

Yes, I'm using the "old" Version 1.2 from F-Droid.
I'm not very familiar with logcat, but the little bit of output I relate
to AndroidCupsPrint isn't very informative:
I/CUPS    (17931): onPrintersDiscovered([])
I/CUPS    (17931): onPrintersDiscovered([])
I/Timeline(17884): Timeline: Activity_launch_request
id:io.github.benoitduffez.cupsprint time:320034264
I/ActivityManager(  996): Displayed
io.github.benoitduffez.cupsprint/.AddPrintersActivity: +245ms
I/Timeline(  996): Timeline: Activity_windows_visible id:
ActivityRecord{36e4040f u0
io.github.benoitduffez.cupsprint/.AddPrintersActivity t4055} time:320034945
I/CUPS    (17931): onPrintersDiscovered([])
I/CUPS    (17931): onPrintersDiscovered([])
I/Timeline(17884): Timeline: Activity_launch_request
id:io.github.benoitduffez.cupsprint time:320507563
I/ActivityManager(  996): START u0 {act=android.intent.action.MAIN
cmp=io.github.benoitduffez.cupsprint/.AddPrintersActivity} from uid 1000
on display 0
V/WindowManager(  996): addAppToken: AppWindowToken{199b1f19
token=Token{3347de60 ActivityRecord{24548263 u0
io.github.benoitduffez.cupsprint/.AddPrintersActivity t4055}}} to
stack=1 task=4055 at 5
V/WindowManager(  996): Adding window Window{502e1bf u0
io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.AddPrintersActivity}
at 29 of 35 (after Window{290af892 u0 PopupWindow:2cbb8a58 EXITING})
I/ActivityManager(  996): Displayed
io.github.benoitduffez.cupsprint/.AddPrintersActivity: +164ms (total
+31s350ms)
I/Timeline(  996): Timeline: Activity_windows_visible id:
ActivityRecord{24548263 u0
io.github.benoitduffez.cupsprint/.AddPrintersActivity t4055} time:320508182
V/WindowManager(  996): Adding window Window{2877b8b6 u0
PopupWindow:6a6c55d} at 29 of 35 (after Window{502e1bf u0
io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.AddPrintersActivity})

I/CUPS    (17931): onPrintersDiscovered([])

Any hints on what to look for?

I will try the latest version as soon as it shows up on F-Droid and give
you feedback.

Thanks & regards
   HB





Am 03.11.2016 um 14:48 schrieb Benoit Duffez:

**Comment by BenoitDuffez** [comment]
Hmm if you're using 1.2 it's not relevant because I fixed a lot of issues since then. We'll have to wait for the 1.3 to come to fdroid.

**Comment by BenoitDuffez** [comment]
The merge was accepted, I guess it's only a matter of time until 1.3 is published there. Please tell me if it's working once you install it. Cheers!

**Comment by pvagner** [comment]
Hello,

I think development of this feature is still in progress.
When relying on MDNS all is working fine.
However here is a description of my setup.

I do have Raspberry pi 3 running arch linux ARM aarch64 with CUPS 2.2.1 at http://192.168.10.171:631/ .
On my Android device Samsung GT-I9100 I am running CM-14.1 unofficial Android 7.1. I've installed ACP from F-Droid because this device is free from gapps.
When I go to Settings -> Print search is in progress however I can press the menu and tap Add printer in the popup menu.
The Add printer activity has two parts. I can just type the ip address into the first text field and press Search for printers button.
After the button is pressed I can see no visible action however I can dismiss Add printer activity by pressing the back button. After the activity is closed I can see printers from the server cups instance added to the list.
However when trying to print I am receiving error saying something like "invalid hostname" and subsequent notice on the print dialog saying this printer is not available.
Trying to capture the logcat I can see ACP is trying to connect to the URL like this:
http://null:631/192.168.10.171:631/printers/printers/Konica
while the correct url would be
http://192.168.10.171:631/printers/Konica
If I enter this seemingly correct url into the bottom half of the Add print activity it's all working fine.
Can you please try to reproduce and fix this please?

**Comment by BenoitDuffez** [comment]
I fucked up the FDroid repo, so it's in a dead state and won't accept updates. Either I'm too stupid or the workflow is obnoxious and abstruse.

So your only luck would be to drop the code in a machine that has the Android SDK properly configured (a linux headless server, a computer running Android Studio, etc) and run the build with the gradle wrapper.

I'm sorry about that.

**Comment by b4free** [comment]
Hi Benoit,



sorry for the late answer - just wanted to let you know that adding a
printer manually does work fine in version 1.3.1.
I got the update from the F-Droid (about three weeks after your mail).

Thanks for your effort and sharing you work on F-Droid!
HB



Am 04.11.2016 um 17:07 schrieb Benoit Duffez:

**Comment by BenoitDuffez** [comment]
Thanks for the feedback!
