### ISSUE TITLE
Need info while connecting to printer(Canon MF210 IPPS printer)

### ISSUE THREAD

**Issue by nsandeep87** [BenoitDuffez/AndroidCupsPrint#36]
Hi,

Thanks for putting this code on git hub. I have a canon MF210 printer that support IPP/IPPS. I have also shared the printer from my MAC. So when I install the android cups printer service on my device, I am able to detect the printer as well as the shared printer of my MAC.

I am able to send print requests through the shared printer of my MAC. But when I select printer directly I am getting 404 error. If I try and pass only the printer ip as url ( instead of http://ipAddress:631/printers, I am getting 406 error( not accessible error). Could you please guide me what the issue could be.

Sandeep

**Comment by BenoitDuffez** [comment]
Maybe there is an issue with IPP printing. Do you have a CUPS server running?

**Comment by nsandeep87** [comment]
I have enabled CUPS interface on my MAC and have added the printers to it. So through my MAC, I am to use it like CUPS server. Please let me know if you need any other info

**Comment by BenoitDuffez** [comment]
Which app version do you use? Could you share your server logs? Device (adb) logs?
Thanks!

**Comment by BenoitDuffez** [comment]
I'm guessing this is a duplicate of #40.

**Comment by BenoitDuffez** [comment]
Closing for now, please comment if this needs another investigation.
