### ISSUE TITLE
No "Print" option under "Settings"

### ISSUE THREAD

**Issue by sv1** [BenoitDuffez/AndroidCupsPrint#41]
Hi, 

I am trying to use your app on a Samsung Galaxy J5 with  Android version 6.0.1 but there is no "Print" option under "Settings".

thanks
AK

**Comment by BenoitDuffez** [comment]
I'm afraid this has nothing to do with the app. I don't know this device and I don't know if it has printing enabled.
On stock Android, it's on the Settings app, System section, "Printing" and print services.

**Comment by sv1** [comment]
Never mind,

it is under Settings > More Connection settings > Printing

please close.

**Comment by BenoitDuffez** [comment]
Thanks for the feedback.
