### ISSUE TITLE
Support for setup that requires login and password?

### ISSUE THREAD

**Issue by TheRadziu** [BenoitDuffez/AndroidCupsPrint#5]
Hey, I just downloaded your app from Play Store and I'd like to ask (if answer is 'No' I'd also like to ask for such a feature/support) if CupsPrint support passworded printers? 
I enabled remote access to my CUPS server (in order to for example restart printer remotely or fix something in cups when I'm not at home) but I put a login requirement since I do not like people looking/messing in my stuff. So the conf is looking like this:
```
<Location />
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>
```

As far as I see CupsPrint do not understand(do not add printer at all)
```
http://login:password@ip:port/printers/myprinter
```
but it works when I leave cups webpage unprotected(which I dont like)

**Comment by TheRadziu** [comment]
Also I think there might be a workaround if CUPS supports it: 
to set up cups <Location /> to require login only when accessed remotely through internet, and do not require it when accessed from internal network (example:10.10.10.x) but I have no idea how to set it up like this.

**Comment by BenoitDuffez** [comment]
That's an interesting feature request. I don't have time right now to test this but I may in the future.

As per the the authentication from internet, I guess it is possible, just have a look [at the doc](https://www.cups.org/documentation.php/doc-1.6/ref-cupsd-conf.html).

**Comment by BenoitDuffez** [comment]
It was verified to be working on my setup. Please reopen if the implementation is not working/suitable for you.

**Comment by pafgoncalves** [comment]
Where do i put the credentials for basic authentication?
Can't find any menu for that.
PS: the printer was added manually with the cups URL.

**Comment by BenoitDuffez** [comment]
Looking at the sources of the fix at https://github.com/BenoitDuffez/AndroidCupsPrint/commit/d7d7e831c70c8fd83ce1dd7955ca0db54d9dfbc7#diff-1079f380a6316a80e82220e317deb2adR357, it appears that the HTTP Basic Auth activity (that requests for login/password) is triggered when the server returns a `FileNotFoundException`.

Can you have a look at the logs and tell me what exception is raised? Maybe there's an other one that I need to add to my `catch` block.

**Comment by pafgoncalves** [comment]
Ok. I need to enable autentication in cups.
```
<Location />
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>
```
Thanks
