### ISSUE TITLE
Imprimante partagée par la livebox

### ISSUE THREAD

**Issue by Jouski** [BenoitDuffez/AndroidCupsPrint#58]
Bonjour,

Tout d'abord merci pour cette application sous licence libre.
Je m'exprime en français, merci de me dire s'il est préférable de discuter en anglais ici.

J'ai installé mon imprimante Brother en la branchant sur le port usb de ma livebox.

Les deux ordinateurs de la maison y ont accès, sous linux, selon le chemin

`ipp14://192.168.1.1/ipp?version=1.0`

et cela fonctionne (la config est documentée ici https://doc.ubuntu-fr.org/livebox#livebox_play )

Depuis l'application AndroidCupsPrint, je n'arrive pas à voir l'imprimante par la recherche automatique (cela dit depuis les ordinateurs linux non plus, j'ai dû entrer l'URL à la main).

J'ai tenté de mettre le même chemin, mais cela ne fonctionne pas. Peut-être que la version de CUPS n'est pas la même ? ou autre chose ?

Bref je ne sais pas comment faire reconnaître l'imprimante du coup.

Pouvez-vous m'aider à y voir clair ?

Merci

**Comment by BenoitDuffez** [comment]
Bonjour,

En français ça ira vu que ça concerne une Livebox.

Pour la découverte automatique il faut avoir mDNS, je ne sais pas si la Livebox supporte cela et si c'est configurable.

Essayez avec l'URL en `http://192.168.1.1/ipp?version=1.0`.
Si ça ne fonctionne pas, c'est que le serveur n'est pas CUPS sur la Livebox. La seule solution c'est d'activer le partage d'imprimante sur l'un de vos postes Linux et de mettre l'IP de ce poste dans l'appli Android. Bien entendu il faudra laisser ce poste allumé si vous voulez imprimer... pas idéal.
Personnellement j'utilise un raspberry.

**Comment by Jouski** [comment]
D'accord, je teste ça demain dès que j'ai la main à nouveau sur l'appareil.
Merci.

**Comment by BenoitDuffez** [comment]
Hello, du nouveau?

**Comment by Jouski** [comment]
Bonjour,

Je viens juste d'avoir accès à nouveau au téléphone (ce n'est pas le mien), et j'ai tenté de faire le test.

Mais je n'arrive pas à créer de nouvelle imprimante. J'accède bien à la page permettant de saisir l'URL et de lui donner un nom, mais après avoir cliqué sur "Ajouter" je reviens immanquablement à la liste des imprimantes (il y en a deux : mes deux précédents essais, que je ne sais d'ailleurs pas supprimer).

**Comment by BenoitDuffez** [comment]
Est-ce que vous utilisez bien la v1.4 du Play Store? Elle vous permet de supprimer les précédents essais.

C'est normal si après avoir ajouté l'imprimante vous revenez sur la liste : il faut maintenant aller dans une application et lancer une impression. Si votre imprimante n'apparaît pas dans cette liste à ce moment là, ou si l'impression ne marche pas, c'est que la Livebox n'est pas compatible.
