### ISSUE TITLE
Printer is detected and shown, but then "currently not availble" in print dialog

### ISSUE THREAD

**Issue by tuxmobil** [BenoitDuffez/AndroidCupsPrint#6]
Like the title says. In the actual print dialog, when selecting the printer, it says the printer is currently not available. No obvious indications as of why.  (Android 6.0.1 to CUPS/Debian)

**Comment by BenoitDuffez** [comment]
The same happened on my setup a few weeks ago but I still couldn't find time to fix this. I didn't update CUPS for some time so I guess Android 6.0.1 is the culprit. I'll have a look into this hopefully sooner than later.
Thanks for the report.

**Comment by BenoitDuffez** [comment]
This happened actually because the server had 2 interfaces and advertised the wrong one over avahi. Do you use mDNS? If so, are you sure about the configuration of your server? Also, check the DNS settings of both the server and the phone. They might diverge and the app can't find the printer.

I'll add some message about the actual error as a toast, anyway.

**Comment by tuxmobil** [comment]
It's my desktop Linux box with CUPS exported. I'll have to check, but am unsure whether I can adjust the name if that's the issue.
Thanks, an error toast will sure be helpful.

**Comment by zilti** [comment]
I have the very same error. Both with the mDNS services CUPS exports as well as a script-generated "AirPrint"-service. I've used that same mDNS service from CUPS to install the printer on my desktop, and it also works with one of the other print apps for Android (forgot the name).

**Comment by nickmdowson** [comment]
Hi, I'm also getting the same error. On CyanogenMod 12.1 (android 5.1.1), F-droid build, installed just a couple days ago.

In addition to this when I try to print, when I go into the print settings in this app / android settings, the printer appears to be greyed out - and I can't click through to it to change settings, etc.

I use the same printer with cups from Linux on my laptop, again with auto-discover, so I'm not sure that the settings / printer is the problem

**Comment by itmike** [comment]
Samething happen for me, but I added my printer manully after enabling ipp. A xerox phaser.

**Comment by maniac103** [comment]
Same issue here. In logcat I can see an IllegalStateException complaining about missing media sizes.

**Comment by maniac103** [comment]
Adding some debug output in checkPrinter() it looks like the response doesn't contain any of the required attributes (media size, resolution etc.), but only general metadata (printer name, change date, icon, etc.). I can print to this printer from a Linux box just fine though, and the CUPS web frontend shows default settings for all of those properties.

Any suggestions for debugging this? I don't really speak IPP :-/

**Comment by maniac103** [comment]
It looks like cups now wants to be passed the list of properties one wants to read. I'll submit a PR for that.
