### ISSUE TITLE
Hostname not verifed

### ISSUE THREAD

**Issue by ab1jx** [BenoitDuffez/AndroidCupsPrint#61]
I don't know if this is an SSL issue or a reverse DNS issue.  I can print over WiFi from another unix box and I don't get anything like this. As far as I know I'm  not running SSL at all (no reason to).  Reverse DNS, well, I have my HP printer plugged into (USB) a Raspberry Pi, which connects by WiFi to an Android phone's WiFi hotspot.  The phone's in control of DNS and DHCP.

Your app is apparently trying to do something unnecessary and it doesn't work.  I'm not sure what.
It's the version that's currently (April 7) on Google Play.

![screenshot_2017-04-07-11-21-28](https://cloud.githubusercontent.com/assets/3131978/24807379/ef6d90ba-1b85-11e7-8854-77c72e70356b.png)

I'm also at alan01346@gmail.com, just happened to have a github account and be on a CUPS mailing list.

**Comment by BenoitDuffez** [comment]
Can you run `curl -vsI http://192.168.43.222:631/` and the same with HTTPS?

**Comment by ab1jx** [comment]
Couldn't resolve the hostnames (IPs) (running curl on the phone).  I
have Debian installed on the phone, didn't set up lpr/CUPS on it
though.  That was under Android with a terminal emulator app.

On the pi:
Maybe I see a problem in that the certificate is using the Pi's
original host name of raspberrypi but I have 2 of them so in each
/etc/hostname I have pi1 and pi2.  DHCP on the AP phone seems to pass
that to DNS, so I can ping, ftp, ssh, etc as pi1 or pi2

in short:
SSL: certificate subject name 'raspberrypi' does not match target host name

The http:
* Rebuilt URL to: http://192.168.43.222:631/
* Hostname was NOT found in DNS cache
*   Trying 192.168.43.222...
* Connected to 192.168.43.222 (192.168.43.222) port 631 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.43.222:631
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 09 Apr 2017 13:06:23 GMT
* Server CUPS/1.7 IPP/2.1 is not blacklisted
< Server: CUPS/1.7 IPP/2.1
< Connection: Keep-Alive
< Keep-Alive: timeout=30
< Content-Language: en_US
< Content-Type: text/html; charset=utf-8
< Last-Modified: Tue, 09 Jun 2015 08:06:54 GMT
< Content-Length: 3697
<
{ [data not shown]
* Connection #0 to host 192.168.43.222 left intact
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
	<TITLE>Home - CUPS 1.7.5</TITLE>
	<LINK REL="STYLESHEET" TYPE="text/css" HREF="/cups.css">
	<LINK REL="SHORTCUT ICON" HREF="/images/cups-icon.png" TYPE="image/png">
</HEAD>
<BODY>
<TABLE CLASS="page" SUMMARY="{title}">
<TR><TD CLASS="body">
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" SUMMARY="">
<TR HEIGHT="36">
<TD><A HREF="http://www.cups.org/" TARGET="_blank"><IMG
SRC="/images/left.gif" WIDTH="64" HEIGHT="36" BORDER="0" ALT=""></A></TD>
<TD CLASS="sel"><A HREF="/">&nbsp;&nbsp;Home&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel"><A
HREF="/admin">&nbsp;&nbsp;Administration&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel"><A HREF="/classes/">&nbsp;&nbsp;Classes&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel"><A
HREF="/help/">&nbsp;&nbsp;Online&nbsp;Help&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel"><A HREF="/jobs/">&nbsp;&nbsp;Jobs&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel"><A HREF="/printers/">&nbsp;&nbsp;Printers&nbsp;&nbsp;</A></TD>
<TD CLASS="unsel" WIDTH="100%"><FORM ACTION="/help/" METHOD="GET"><INPUT
TYPE="SEARCH" NAME="QUERY" SIZE="20" PLACEHOLDER="Search Help"
AUTOSAVE="org.cups.help" RESULTS="20"></FORM></TD>
<TD><IMG SRC="/images/right.gif" WIDTH="4" HEIGHT="36" ALT=""></TD>
</TR>
</TABLE>

<TABLE CLASS="indent" SUMMARY="">
<TR><TD STYLE="padding-right: 20px;">

<H1>CUPS 1.7.5</H1>

<P>CUPS is the standards-based, open source printing system developed by
<A HREF="http://www.apple.com/">Apple Inc.</A> for OS<SUP>&reg;</SUP> X and
other UNIX<SUP>&reg;</SUP>-like operating systems.</P>

</TD>
<TD><A HREF="http://www.cups.org/"><IMG SRC="images/cups-icon.png" WIDTH="128"
HEIGHT="128" ALT="CUPS"></A></TD>
</TR>
</TABLE>

<TABLE CLASS="indent" SUMMARY="">
<TR><TD VALIGN="top" STYLE="border-right: dotted thin #cccccc;
padding-right: 20px;">

<H2>CUPS for Users</H2>

<P><A HREF="help/overview.html">Overview of CUPS</A></P>

<P><A HREF="help/options.html">Command-Line Printing and Options</A></P>

<P><A HREF="help/whatsnew.html">What's New in CUPS 1.7</A></P>

<P><A HREF="http://www.cups.org/lists.php?LIST=cups">User Forum</A></P>

</TD><TD VALIGN="top" STYLE="border-right: dotted thin #cccccc;
padding-left: 20px; padding-right: 20px;">

<H2>CUPS for Administrators</H2>

<P><A HREF="admin">Adding Printers and Classes</A></P>

<P><A HREF="help/policies.html">Managing Operation Policies</A></P>

<P><A HREF="help/accounting.html">Printer Accounting Basics</A></P>

<P><A HREF="help/security.html">Server Security</A></P>

<P><A HREF="help/kerberos.html">Using Kerberos Authentication</A></P>

<P><A HREF="help/network.html">Using Network Printers</A></P>

<P><A HREF="help/ref-cupsd-conf.html">cupsd.conf Reference</A></P>

</TD><TD VALIGN="top" STYLE="padding-left: 20px;">

<H2>CUPS for Developers</H2>

<P><A HREF="help/api-overview.html">Introduction to CUPS Programming</A></P>

<P><A HREF="help/api-cups.html">CUPS API</A></P>

<P><A HREF="help/api-filter.html">Filter and Backend Programming</A></P>

<P><A HREF="help/api-httpipp.html">HTTP and IPP APIs</A></P>

<P><A HREF="help/api-ppd.html">PPD API</A></P>

<P><A HREF="help/api-raster.html">Raster API</A></P>

<P><A HREF="help/ref-ppdcfile.html">PPD Compiler Driver Information
File Reference</A></P>

<P><A HREF="http://www.cups.org/lists.php?LIST=cups-devel">Developer
Forum</A></P>

</TD></TR>
</TABLE>

</TD></TR>
<TR><TD>&nbsp;</TD></TR>
<TR><TD CLASS="trailer">CUPS and the CUPS logo are trademarks of
<A HREF="http://www.apple.com">Apple Inc.</A> Copyright 2007-2014 Apple
Inc. All rights reserved.</TD></TR>
</TABLE>
</BODY>
</HTML>

The https:
* Rebuilt URL to: https://192.168.43.222:631/
* Hostname was NOT found in DNS cache
*   Trying 192.168.43.222...
* Connected to 192.168.43.222 (192.168.43.222) port 631 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: CN=raspberrypi
* 	 start date: 2016-08-06 14:22:23 GMT
* 	 expire date: 2026-08-04 14:22:23 GMT
* SSL: certificate subject name 'raspberrypi' does not match target
host name '192.168.43.222'
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
} [data not shown]


On 4/9/17, Benoit Duffez <notifications@github.com> wrote:
> Can you run `curl -vsI http://192.168.43.222:631/` and the same with HTTPS?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BenoitDuffez/AndroidCupsPrint/issues/61#issuecomment-292783302


-- 
-------------
No, I won't  call it "climate change", do you have a "reality problem"? - AB1JX
Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach

**Comment by BenoitDuffez** [comment]
When a printer is available both over HTTP and HTTPS, the app automatically uses HTTPS.

Your certificate is not valid (the SN=raspberry doesn't match the IP address).

So either switch off SSL on the CUPS server, or ensure the certificate is valid. You could also add an exception in the app so that the certificate is trusted anyway.

**Comment by ab1jx** [comment]
Uninstalled.

On 4/9/17, Benoit Duffez <notifications@github.com> wrote:
> Closed #61.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BenoitDuffez/AndroidCupsPrint/issues/61#event-1035470365


-- 
-------------
No, I won't  call it "climate change", do you have a "reality problem"? - AB1JX
Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach  Impeach

**Comment by BenoitDuffez** [comment]
I'm sorry if you thought my reply was rude. I was just saying that the issue you are facing is normal and expected, and it isn't a bug in the app.
So I'm closing the GitHub bug. That doesn't mean the discussion is closed or that I am refusing to help.

**Comment by BenoitDuffez** [comment]
Please also understand that this app is free (e.g. I don't make anything from it) and I do this in my free time.
Blackmailing with "uninstall" threats has zero effect here. If you don't like the app, you are free to do whatever you like.
