### ISSUE TITLE
Can't enter actual hostname, just IP address

### ISSUE THREAD

**Issue by dueringa** [BenoitDuffez/AndroidCupsPrint#63]
F-Droid build 1.3.1:
Via Menu -> add printer, in the IP address / hostname field, you somehow lock the keyboard so only an IP address can be entered, no hostname.
I would like to enter an actual hostname.

**Comment by BenoitDuffez** [comment]
Weird it's `textUri|number`: https://github.com/BenoitDuffez/AndroidCupsPrint/blob/fdroid/app/src/main/res/layout/add_printers.xml

Text that will be used as a URI. Corresponds to TYPE_CLASS_TEXT | TYPE_TEXT_VARIATION_URI.

So you should be able to enter text.

What is the device / OS version ?

**Comment by dueringa** [comment]
I'm running LineageOS 13.0 (self-built) on an Asus Zenfone 2 (Z00T). 
I tested the behavior with the AOSP keyboard, SwiftKey, Hackers Keyboard and AnySoft Keyboard. 
I also have a Samsung Galaxy S III with LineageOS 14.1. I get the same behavior. 
With the AOSP keyboard, it looks like this:

**Comment by BenoitDuffez** [comment]
What AOSP is 13.0 based on?

Do you have dual boot or can you test with vanilla Android?

**Comment by dueringa** [comment]
LineageOS 13 is based on Android 6.0.1 (Marshmallow, API level 23).

I don't have dual boot set up or another phone with stock or vanilla Android, so I can't test that.

The Play Store version (1.4.0) shows the same behavior for me.

**Comment by BenoitDuffez** [comment]
Can you compile? If so, change the input type to text or just remove the XML attr. See what happens.

**Comment by dueringa** [comment]
Okay, I built it myself, these are the results:

Removing the attribute completely: normal keyboard appears
Setting the attribute to `android:inputType="textUri"`: Normal keyboard appears
Setting the attribute to `android:inputType="number|textUri"`: I can only enter numbers

I also created an emulator with Intel Atom 64 processor and Android 6 image. I can reproduce the behavior from my phone: 
![emulator](https://cloud.githubusercontent.com/assets/271125/25045468/d407f3e0-212c-11e7-9d90-8c40ba72c791.png)

**Comment by dueringa** [comment]
From what I read into the documentation (https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType), those two flags can't / shouldn't be combined at all, since the documentation for these flags doesn't say "Can be combined with..."...
So I think Android uses the "smaller range"?

**Comment by BenoitDuffez** [comment]
Hmm, interesting.
Huge thanks for the effort you put into this.

I'll change to `textUri` (or submit a PR on `develop` and I'll merge)

**Comment by BenoitDuffez** [comment]
Don't know which commit fixed this, but the field is now `textUri`.

**Comment by stuaxo** [comment]
Hi @BenoitDuffez 
   Is this version going to be up on google play soon?

S

**Comment by BenoitDuffez** [comment]
Yes
