### ISSUE TITLE
CUPS Printing A4 Format

### ISSUE THREAD

**Issue by Tschoran** [BenoitDuffez/AndroidCupsPrint#78]
In the printing menu there is the A4 format twice, i think one of it should be A3?

**Comment by BenoitDuffez** [comment]
Can you tell me if the printer sends proper paper information? Like with a tcpdump trace or something

**Comment by Tschoran** [comment]
this is what i meant (see attachment).

---- Benoit Duffez schrieb ----

**Comment by BenoitDuffez** [comment]
There is no attachment.

**Comment by Tschoran** [comment]
i attached a screenshot but it seems that it didn’t work.
can you give me your personal email address or something else so i can send it to you?

**Comment by BenoitDuffez** [comment]
benoit.duffez@upactivity.com

**Comment by BenoitDuffez** [comment]
Please update this ticket or I'll close it.
