### ISSUE TITLE
Connect Exception

### ISSUE THREAD

**Issue by anki1427** [BenoitDuffez/AndroidCupsPrint#79]
Not Able to connect with my printer issue is failed to connect i.e connect exception 
printer id is http://[fe80::cad3:ffff:feb0:c01b]:631/printers/print

**Comment by BenoitDuffez** [comment]
Do you have more information? Application logs, server logs, versions, screenshots, etc.

From this I can't tell which is failing (server? printer? app? router?) and how it is failing.

**Comment by anki1427** [comment]
I am able to search printer on the same network but i am not able to connect to the printer its throwing the connect exception with the printer when i am going to print something.
Please see the logs.And i am on the same network as of the printer.
![screenshot from 2017-05-30 18 05 20](https://cloud.githubusercontent.com/assets/16552517/26583403/b91f05fa-4562-11e7-9372-f358e6822140.png)
![screenshot from 2017-05-30 18 04 49](https://cloud.githubusercontent.com/assets/16552517/26583404/b921964e-4562-11e7-9568-ba7acd6f125d.png)

**Comment by BenoitDuffez** [comment]
Which version do you use? It used to have problems with IPv6 but I fixed this a while back.

**Comment by BenoitDuffez** [comment]
Is this still applicable? Should I close?
