### ISSUE TITLE
Support printing over VPN

### ISSUE THREAD

**Issue by BenoitDuffez** [BenoitDuffez/AndroidCupsPrint#81]
One user left a feedback saying it works except over a VPN.

**Comment by danifr** [comment]
It worked perfectly* fine for me.

CUPS 2.2.6 server on a Raspberry Pi B 1
Android 8.1
AndroidCupsPrint 1.4

![imagen](https://user-images.githubusercontent.com/7135482/34620011-5a88a8cc-f244-11e7-85be-6e3d0bdce9da.png)

I don´t think there is an issue here :)

\* it took like 3 minutes to print but other than that no problem

**Comment by BenoitDuffez** [comment]
Thanks a lot to have tested this, too lazy to do it ;)
