### ISSUE TITLE
Error "Couldn't find job [id], is it already finished?" occurs, even though printing works

### ISSUE THREAD

**Issue by jnk22** [BenoitDuffez/AndroidCupsPrint#87]
Hello there,

I tried your app today and printing itself already works!

Unfortunately I get the error "Couldn't find job [id], is it already finished?" for every print job that I do. It actually prints the document and then fails with showing the error message over and over again. This actually seems to break my CUPS server itself a while after, as CPU load goes up to 100% for that process somehow.

I checked the code and found a value called JOB_CHECK_POLLING_INTERVAL = 5000. I guess this is the time to keep checking the job id?

And looking some more into it, it seems like this error occurs, when there is a 4xx http error coming from the server itself, correct? If so, maybe I would have to correct my CUPS configuration to allow to check the job ID. Most of my limits for CUPS require a "valid user" only. Is there any specific thing like "Print-Job", "Create-Job" that I need to make available without any checks like "@OWNER, @SYSTEM, valid-user" so the polling doesn't fail?

IMO it would be better to stop polling the job state after a few failed checks anyway, let's say 3 or 4 times and then output sth. like "Couldn't check job state, stopping." or so. Without that it seems like it never ends when it can't get the state of the job at all.

This was tested on 2 different Samsung Galaxy S4 (Android 5.0.1). I don't know if this could be a specific problem for that phone, but for me it seems like some other error.

Thanks for reading and thank you for all your work!

**Comment by BenoitDuffez** [comment]
I don't know exactly. If you can reproduce and show me the Android and server logs, that would be great. I haven't seen this personally.

**Comment by BenoitDuffez** [comment]
Please reopen with more information, should you have some.

**Comment by chrisapps4u** [comment]
I think the problem is the "valid user"! Every communication to the cups server is without a user name. It's not implemented in cups4j. So we ONLY can read the job state if we can communicate without a user name. A implementation of user name could be something for the future.
