### ISSUE TITLE
404 page for printer

### ISSUE THREAD

**Issue by pchestek** [BenoitDuffez/AndroidCupsPrint#91]
Android CUPS Print autodetects printer and when using print command there is a popup that says "Search found 1 printer." But then there is a second message that says "The printer name was not found on the server (HTTP 404). Please check its name." Samsung Galaxy Tab E, Android 7.1.1, trying to print to Brother DW-2270DW. Manually adding via IP address doesn't seem to do anything. Thanks.

**Comment by BenoitDuffez** [comment]
Are you sure this is cups? This looks like a customized version that we often find on set top boxes or similar hardware. Other than that I would have to investigate when I have time.

**Comment by pchestek** [comment]
Thanks for your answer. Downloaded from Google Play.

**Comment by BenoitDuffez** [comment]
I meant the version of the CUPS daemon on your print server. The device your printer is connected to.

**Comment by pchestek** [comment]
Then it's my mistake. There is no print server, I was connecting through a wireless router directly to the printer. Thanks.

**Comment by BenoitDuffez** [comment]
OK. I don't know if the printer is compatible then.

Can you retrieve Android logs? Possibly printer logs would be useful too, however I'm guessing you have no access to them.

**Comment by BenoitDuffez** [comment]
Please comment if you need support on this
