### ISSUE TITLE
Printing only blank pages on Brother

### ISSUE THREAD

**Issue by pablos91** [BenoitDuffez/AndroidCupsPrint#97]
Hi. Cups driver is properly connecting to the printer but it only prints blank pages are there any way to make this work ?

My printer is Brother HL-1112e

Thanks

**Comment by BenoitDuffez** [comment]
I assume other devices can print just fine? Is there any issue with color/black ink selection maybe?

**Comment by BenoitDuffez** [comment]
Any details on how to reproduce? Any logs?

**Comment by BenoitDuffez** [comment]
Please reopen if you have more information.
